print('\033[1:30m====== Desafio 4 ======\033[m')
algo = input('Digite qualquer coisa: ')
print('O que você digitou é do tipo {}'.format(type(algo)))
print('É simplesmente um espaço?', algo.isspace())
print('É alfanumérico?', algo.isalnum())
print('É número?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('Está em maiúsculas?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Está capitalizada?', algo.istitle())
